steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['--version']
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: [ 'test' ]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: [ "package", "-Dmaven.test.skip=true" ]
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/family-video-diary/mavendockercontainer', '--build-arg=JAR_FILE=target/my-maven-docker-project', '.']
images: ['gcr.io/family-video-diary/mavendockercontainer']